= Do your own research
Wei Tang <wei@that.world>
:license: CC-BY-SA-4.0
:license-code: Apache-2.0

[meta="description"]
This article is of things that you should be aware of before making an
investment decision on Kulupu.

Everything noted here can also be found in various places including
Kulupu discussion channels, official READMEs and other docs, etc. We
document them again in this DYOR article to further reduce the chance
that investors blindly invest in Kulupu.

A side note on this article is that it only documents the *mostly
negative aspects* of Kulupu. You can find postive aspects of Kulupu in
other technical documentations.

* *Kulupu is a cryptocurrency without a roadmap.* Developers behind
  Kulupu explicitly do not release any roadmap to avoid promising
  things it may not manage to implement.
* *Kulupu has a high yearly inflation rate right now.* As a blockchain
  without any pre-mine, high inflation in the first several years are
  unavoidable. Currently, we're in the second year since the Kulupu
  launch, and the yearly inflation is 50%.
* *Kulupu does not have full-time developers.* Kulupu started as a
  side project of Wei Tang. Since launch, it has been maintained and
  developed by volunteers. With no budget or investment for the core
  team, no developers work on Kulupu full-time.
