= Governance
Wei Tang <wei@that.world>
:license: CC-BY-SA-4.0
:license-code: Apache-2.0

[meta="description"]
This page documents the current and future referendums of the Kulupu
network.

== Current referendum

Referendum No. 6 is to set the *voluntary taxation* rate of Kulupu
network to _20%_. The current taxation rate is 0%.

The voting begins on block 161280 (28 Aug, 2020) and ends on block
171360 (4 Sep, 2020).

== Future referenda

The likely schedule of future referenda are:

* *Grand View Garden* runtime upgrade, enabling signed mining and
  reward block. The voting begins on block 171360 (4 Sep, 2020) and
  ends on 181440 (11 Sep, 2020).
* Reduce *block reward* to _30 KLP_ at block 205600. The current block
  reward is 60 KLP and is scheduled to be reduced to 54 KLP at block
  200000. The voting begins on block 181440 (11 Sep, 2020) and ends on
  block 191520 (18 Sep, 2020).

== Past referenda

* *Referendum No. 0*: A no-op referendum that writes an on-chain
  remark, with text "The New Era of Kulupu". Passed.
* *Referendum No. 1*: *Sky Island 68* runtime upgrade. Passed and
  executed.
* *Referendum No. 2*: *Red Coast Base* runtime upgrade. Passed and
  executed.
* *Referendum No. 3*: *Seeker Camp* runtime upgrade. Passed and
  executed.
* *Referendum No. 4*: Reduce *block reward* to _54 KLP_ at block
  200000. The previous block reward of 60 KLP. Passed.
* *Referendum No. 5*: *Red Gate* runtime upgrade. Passed.
