= Governance
Wei Tang <wei@that.world>
:license: CC-BY-SA-4.0
:license-code: Apache-2.0

[meta="description"]
This page documents the current and future referendums of the Kulupu
network.

== Current referendum

Referendum No. 10 is to set the balance of treasury to _100000
KLP_. Note that technically, this can either mint to treasury or burn
from treasury, depending on how many coins treasury will have at the
activation block.

The voting begins on block 191520 (18 Sep, 2020) and ends on block
201600 (26 Sep, 2020).

== Past referenda

* *Referendum No. 0*: A no-op referendum that writes an on-chain
  remark, with text "The New Era of Kulupu". _Passed._
* *Referendum No. 1*: *Sky Island 68* runtime upgrade. _Passed and
  executed._
* *Referendum No. 2*: *Red Coast Base* runtime upgrade. _Passed and
  executed._
* *Referendum No. 3*: *Seeker Camp* runtime upgrade. _Passed and
  executed._
* *Referendum No. 4*: Reduce *block reward* to _54 KLP_ at block
  200000 (24 Sep, 2020). The previous block reward was
  60 KLP. _Passed._
* *Referendum No. 5*: *Red Gate* runtime upgrade. _Passed._
* *Referendum No. 6*: Set the *voluntary taxation rate* to 20%. The
  previous rate was 0%. _Passed._
* *Referendum No. 7*: Emergency referendum tabled to fix an issue in
  Kulupu's scheduler runtime module. _Fixed and passed._
* *Referendum No. 8*: *Grand View Garden* runtime upgrade. _Passed._
* *Referendum No. 9*: Reduce *block reward* to _30 KLP_ at block
  205600 (28 Sep, 2020). _Passed._
